// 온보딩 카테고리 + 소모품 템플릿 데이터

export const ALL_CATEGORIES = [
  { key: '욕실',     icon: '🛁', default: true },
  { key: '거실',     icon: '🛋️', default: true },
  { key: '주방',     icon: '🍳', default: true },
  { key: '세탁실',   icon: '🧺', default: true },
  { key: '청소',     icon: '🧹', default: true },
  { key: '침실',     icon: '🛏', default: false },
  { key: '드레스룸', icon: '👔', default: false },
  { key: '건강',     icon: '💊', default: false },
  { key: '반려동물', icon: '🐾', auto: 'pets' },
  { key: '유아용품', icon: '🍼', auto: 'infants' },
]

export const ITEMS_BY_CATEGORY = {
  '욕실': [
    { name: '화장지',     icon: '🧻', brand: '유한킴벌리', spec: '3겹 30롤',  baselineDays: 60 },
    { name: '샴푸',       icon: '🚿', brand: '팬틴',       spec: '400ml',     baselineDays: 30 },
    { name: '린스',       icon: '🧴', brand: '팬틴',       spec: '400ml',     baselineDays: 45 },
    { name: '바디워시',   icon: '🧼', brand: '다우니',     spec: '500ml',     baselineDays: 30 },
    { name: '치약',       icon: '🪥', brand: '2080',       spec: '120g',      baselineDays: 45 },
    { name: '칫솔',       icon: '🪥', brand: '오랄비',     spec: '1개',       baselineDays: 90 },
    { name: '면도기',     icon: '🪒', brand: '질레트',     spec: '1개',       baselineDays: 90 },
    { name: '면도크림',   icon: '🪒', brand: '질레트',     spec: '200ml',     baselineDays: 60 },
    { name: '욕실세제',   icon: '🧽', brand: '홈스타',     spec: '500ml',     baselineDays: 60 },
    { name: '변기세정제', icon: '🚽', brand: '후레쉬',     spec: '1개',       baselineDays: 90 },
    { name: '바디로션',   icon: '🧴', brand: '',           spec: '400ml',     baselineDays: 45 },
    { name: '폼클렌징',   icon: '🧼', brand: '',           spec: '150ml',     baselineDays: 30 },
    { name: '면봉',       icon: '🩹', brand: '',           spec: '200개입',   baselineDays: 90 },
    { name: '화장솜',     icon: '🧻', brand: '',           spec: '80매',      baselineDays: 30 },
    { name: '생리대',     icon: '🩹', brand: '',           spec: '1팩',       baselineDays: 30 },
  ],
  '거실': [
    { name: '건전지',           icon: '🔋', brand: '에너자이저', spec: 'AA 8개',   baselineDays: 50 },
    { name: '공기청정기 필터',   icon: '🌬️', brand: '',           spec: '1개',      baselineDays: 90 },
    { name: '에어컨 필터',       icon: '❄️', brand: '',           spec: '1개',      baselineDays: 90 },
    { name: '방향제',           icon: '🌸', brand: '페브리즈',   spec: '1개',      baselineDays: 30 },
    { name: '섬유탈취제',       icon: '👕', brand: '페브리즈',   spec: '300ml',    baselineDays: 30 },
    { name: '먼지떨이',         icon: '🪶', brand: '',           spec: '1개',      baselineDays: 180 },
    { name: '모기향',           icon: '🦟', brand: '',           spec: '1개',      baselineDays: 60 },
    { name: '방습제',           icon: '💧', brand: '',           spec: '1개',      baselineDays: 60 },
    { name: '전구',             icon: '💡', brand: '필립스',     spec: 'LED 1개',  baselineDays: 365 },
  ],
  '주방': [
    { name: '주방세제',       icon: '🍽️', brand: '트리오',  spec: '500ml',     baselineDays: 60 },
    { name: '수세미',         icon: '🧽',  brand: '',        spec: '1개',       baselineDays: 30 },
    { name: '키친타올',       icon: '🧻',  brand: '스카트',  spec: '150매',     baselineDays: 20 },
    { name: '랩',             icon: '📦',  brand: '',        spec: '1개',       baselineDays: 90 },
    { name: '지퍼백',         icon: '🛍️', brand: '',        spec: '50매',      baselineDays: 30 },
    { name: '알루미늄호일',   icon: '🥫',  brand: '',        spec: '1개',       baselineDays: 90 },
    { name: '식기세척기세제', icon: '✨',  brand: '피니쉬',  spec: '1kg',       baselineDays: 60 },
    { name: '위생장갑',       icon: '🧤',  brand: '',        spec: '100매',     baselineDays: 30 },
    { name: '종이컵',         icon: '🥤',  brand: '',        spec: '50개',      baselineDays: 30 },
    { name: '이쑤시개',       icon: '🪥',  brand: '',        spec: '1통',       baselineDays: 120 },
    { name: '빨대',           icon: '🥤',  brand: '',        spec: '100개',     baselineDays: 60 },
  ],
  '세탁실': [
    { name: '세탁세제',   icon: '🧴', brand: '피죤',     spec: '3kg',       baselineDays: 90 },
    { name: '섬유유연제', icon: '💧', brand: '다우니',   spec: '2L',        baselineDays: 60 },
    { name: '표백제',     icon: '⚪', brand: '옥시크린', spec: '1kg',       baselineDays: 120 },
    { name: '드라이시트', icon: '🍃', brand: '다우니',   spec: '80매',      baselineDays: 40 },
    { name: '세탁망',     icon: '🧺', brand: '',         spec: '1개',       baselineDays: 180 },
    { name: '의류탈취제', icon: '👕', brand: '페브리즈', spec: '370ml',     baselineDays: 30 },
  ],
  '청소': [
    { name: '쓰레기봉투',       icon: '🗑️', brand: '',         spec: '20L 50매', baselineDays: 25 },
    { name: '재활용봉투',       icon: '♻️',  brand: '',         spec: '50매',     baselineDays: 30 },
    { name: '청소포',           icon: '🧽',  brand: '',         spec: '30매',     baselineDays: 15 },
    { name: '락스',             icon: '🧴',  brand: '유한락스', spec: '1L',       baselineDays: 60 },
    { name: '욕실곰팡이제거제', icon: '🧫',  brand: '',         spec: '500ml',    baselineDays: 90 },
    { name: '먼지떨이',         icon: '🪶',  brand: '',         spec: '1개',      baselineDays: 180 },
    { name: '고무장갑',         icon: '🧤',  brand: '',         spec: '1켤레',    baselineDays: 60 },
    { name: '행주',             icon: '🧹',  brand: '',         spec: '3매',      baselineDays: 30 },
    { name: '스펀지',           icon: '🧽',  brand: '',         spec: '1개',      baselineDays: 30 },
    { name: '유리세정제',       icon: '🪟',  brand: '',         spec: '500ml',    baselineDays: 90 },
    { name: '바닥청소포',       icon: '🧹',  brand: '',         spec: '30매',     baselineDays: 20 },
  ],
  '침실': [
    { name: '방향제',     icon: '🌸', brand: '페브리즈', spec: '1개',       baselineDays: 30 },
    { name: '섬유탈취제', icon: '👕', brand: '페브리즈', spec: '300ml',     baselineDays: 30 },
    { name: '모기향',     icon: '🦟', brand: '',         spec: '1개',       baselineDays: 60 },
    { name: '모기패치',   icon: '🦟', brand: '',         spec: '24매',      baselineDays: 30 },
    { name: '방습제',     icon: '💧', brand: '',         spec: '3개입',     baselineDays: 90 },
    { name: '침구탈취제', icon: '🛏', brand: '',         spec: '400ml',     baselineDays: 30 },
  ],
  '드레스룸': [
    { name: '방충제',   icon: '🛡️', brand: '',   spec: '1개',     baselineDays: 180 },
    { name: '옷걸이',   icon: '👔',  brand: '',   spec: '10개',    baselineDays: 365 },
    { name: '구두약',   icon: '👞',  brand: '',   spec: '1개',     baselineDays: 180 },
    { name: '실리카겔', icon: '💧',  brand: '',   spec: '10개입',  baselineDays: 90 },
  ],
  '유아용품': [
    { name: '기저귀',           icon: '🧒', brand: '',   spec: '1팩',     baselineDays: 7 },
    { name: '아기물티슈',       icon: '🧻', brand: '',   spec: '80매',    baselineDays: 5 },
    { name: '기저귀봉투',       icon: '🗑️', brand: '',   spec: '200매',   baselineDays: 14 },
    { name: '분유',             icon: '🍼', brand: '',   spec: '800g',    baselineDays: 14 },
    { name: '젖병세정제',       icon: '🧴', brand: '',   spec: '500ml',   baselineDays: 30 },
    { name: '아기샴푸',         icon: '🧴', brand: '',   spec: '350ml',   baselineDays: 30 },
    { name: '아기로션',         icon: '🧴', brand: '',   spec: '300ml',   baselineDays: 20 },
    { name: '아기바디워시',     icon: '🧴', brand: '',   spec: '350ml',   baselineDays: 30 },
    { name: '아기면봉',         icon: '🩹', brand: '',   spec: '200개입', baselineDays: 60 },
    { name: '거즈손수건',       icon: '🧻', brand: '',   spec: '10매',    baselineDays: 30 },
    { name: '아기세탁세제',     icon: '🧴', brand: '',   spec: '1.5L',    baselineDays: 30 },
    { name: '아기섬유유연제',   icon: '💧', brand: '',   spec: '1.5L',    baselineDays: 30 },
    { name: '아기연고',         icon: '🩹', brand: '',   spec: '1개',     baselineDays: 60 },
    { name: '체온계배터리',     icon: '🔋', brand: '',   spec: '2개',     baselineDays: 180 },
    { name: '모기패치(아기용)', icon: '🦟', brand: '',   spec: '24매',    baselineDays: 20 },
  ],
  '건강': [
    { name: '밴드',       icon: '🩹', brand: '',   spec: '20매',   baselineDays: 90 },
    { name: '마스크',     icon: '😷', brand: '',   spec: '50매',   baselineDays: 30 },
    { name: '손소독제',   icon: '🧴', brand: '',   spec: '500ml',  baselineDays: 30 },
    { name: '소독솜',     icon: '🩹', brand: '',   spec: '40매',   baselineDays: 60 },
  ],
  '반려동물': [
    { name: '펫패드',         icon: '🐾', brand: '',   spec: '50매',    baselineDays: 1,   petItem: true },
    { name: '사료',           icon: '🍖', brand: '',   spec: '2kg',     baselineDays: 1,   petItem: true },
    { name: '간식',           icon: '🦴', brand: '',   spec: '1봉',     baselineDays: 3,   petItem: true },
    { name: '반려동물샴푸',   icon: '🧴', brand: '',   spec: '500ml',   baselineDays: 30,  petItem: true },
    { name: '배변봉투',       icon: '🗑️', brand: '',   spec: '100매',   baselineDays: 2,   petItem: true },
    { name: '모래/펫시트',    icon: '🪣', brand: '',   spec: '1봉',     baselineDays: 10,  petItem: true },
    { name: '구충제',         icon: '💊', brand: '',   spec: '1개',     baselineDays: 90,  petItem: true },
    { name: '칫솔(펫용)',     icon: '🪥', brand: '',   spec: '1개',     baselineDays: 30,  petItem: true },
  ],
}
