-- menu_recipes: 메뉴추천용 레시피 카탈로그
-- meal_type: 끼니 (아침/점심/저녁/야식) — 한 메뉴가 여러 끼니에 걸칠 수 있음
-- ingredients: [{name, emoji, keyword}] — keyword는 쿠팡 검색에 사용
-- milkit_keyword: 쿠팡 밀키트 검색 키워드 (없으면 NULL)
-- tags: ["간단","10분","혼밥"] 등 자유 라벨
CREATE TABLE IF NOT EXISTS public.menu_recipes (
  id              bigserial PRIMARY KEY,
  name            text NOT NULL,
  meal_type       text[] NOT NULL,
  category        text,
  ingredients     jsonb NOT NULL DEFAULT '[]'::jsonb,
  milkit_keyword  text,
  tags            text[] DEFAULT '{}',
  created_at      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_menu_recipes_name ON public.menu_recipes (name);
CREATE INDEX IF NOT EXISTS idx_menu_recipes_meal_type ON public.menu_recipes USING GIN (meal_type);

-- RLS: 카탈로그성 데이터라 누구나 read 가능
ALTER TABLE public.menu_recipes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "menu_recipes_select" ON public.menu_recipes;
CREATE POLICY "menu_recipes_select" ON public.menu_recipes
  FOR SELECT TO authenticated USING (true);

-- ── 데이터 삽입 ─────────────────────────────────────────────────────
-- 아침 (47)
INSERT INTO public.menu_recipes (name, meal_type, category, ingredients, milkit_keyword, tags) VALUES
('계란후라이', ARRAY['아침'], '한식', '[{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"식용유","emoji":"🫙","keyword":"식용유"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', NULL, ARRAY['간단','5분','혼밥']),
('스크램블에그', ARRAY['아침'], '양식', '[{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', NULL, ARRAY['간단','5분']),
('계란말이', ARRAY['아침'], '한식', '[{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', NULL, ARRAY['간단','10분']),
('토스트', ARRAY['아침'], '양식', '[{"name":"식빵","emoji":"🍞","keyword":"식빵"},{"name":"버터","emoji":"🧈","keyword":"버터"},{"name":"딸기잼","emoji":"🍓","keyword":"딸기잼"}]', NULL, ARRAY['간단','5분']),
('프렌치토스트', ARRAY['아침'], '양식', '[{"name":"식빵","emoji":"🍞","keyword":"식빵"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', NULL, ARRAY['간단','10분']),
('아보카도토스트', ARRAY['아침'], '양식', '[{"name":"식빵","emoji":"🍞","keyword":"식빵"},{"name":"아보카도","emoji":"🥑","keyword":"아보카도"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"레몬","emoji":"🍋","keyword":"레몬"}]', NULL, ARRAY['건강','10분']),
('오트밀', ARRAY['아침'], '양식', '[{"name":"오트밀","emoji":"🌾","keyword":"오트밀"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"바나나","emoji":"🍌","keyword":"바나나"},{"name":"꿀","emoji":"🍯","keyword":"꿀"}]', NULL, ARRAY['건강','간단','5분']),
('그래놀라', ARRAY['아침'], '양식', '[{"name":"그래놀라","emoji":"🌾","keyword":"그래놀라"},{"name":"그릭요거트","emoji":"🥛","keyword":"그릭요거트"},{"name":"블루베리","emoji":"🫐","keyword":"블루베리"}]', NULL, ARRAY['건강','간단']),
('팬케이크', ARRAY['아침'], '양식', '[{"name":"핫케이크가루","emoji":"🥞","keyword":"핫케이크가루"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"메이플시럽","emoji":"🍯","keyword":"메이플시럽"}]', NULL, ARRAY['주말','20분']),
('와플', ARRAY['아침'], '양식', '[{"name":"와플믹스","emoji":"🧇","keyword":"와플믹스"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', NULL, ARRAY['주말','20분']),
('흰죽', ARRAY['아침'], '한식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"참기름","emoji":"🫙","keyword":"참기름"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', '죽 밀키트', ARRAY['건강','회복식']),
('야채죽', ARRAY['아침'], '한식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"애호박","emoji":"🥬","keyword":"애호박"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '야채죽 밀키트', ARRAY['건강','회복식']),
('닭죽', ARRAY['아침'], '한식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"닭가슴살","emoji":"🍗","keyword":"닭가슴살"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '닭죽 밀키트', ARRAY['건강','든든']),
('샌드위치', ARRAY['아침','점심'], '양식', '[{"name":"식빵","emoji":"🍞","keyword":"식빵"},{"name":"햄","emoji":"🥩","keyword":"햄"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"양상추","emoji":"🥬","keyword":"양상추"},{"name":"마요네즈","emoji":"🫙","keyword":"마요네즈"}]', NULL, ARRAY['간단','10분']),
('클럽샌드위치', ARRAY['아침'], '양식', '[{"name":"식빵","emoji":"🍞","keyword":"식빵"},{"name":"닭가슴살","emoji":"🍗","keyword":"닭가슴살"},{"name":"베이컨","emoji":"🥓","keyword":"베이컨"},{"name":"양상추","emoji":"🥬","keyword":"양상추"},{"name":"토마토","emoji":"🍅","keyword":"토마토"}]', NULL, ARRAY['든든','20분']),
('바나나쉐이크', ARRAY['아침'], '양식', '[{"name":"바나나","emoji":"🍌","keyword":"바나나"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"꿀","emoji":"🍯","keyword":"꿀"}]', NULL, ARRAY['간단','5분','건강']),
('스무디볼', ARRAY['아침'], '양식', '[{"name":"냉동딸기","emoji":"🍓","keyword":"냉동딸기"},{"name":"바나나","emoji":"🍌","keyword":"바나나"},{"name":"그릭요거트","emoji":"🥛","keyword":"그릭요거트"},{"name":"그래놀라","emoji":"🌾","keyword":"그래놀라"}]', NULL, ARRAY['건강','간단']),
('미역국', ARRAY['아침'], '한식', '[{"name":"미역","emoji":"🌿","keyword":"미역"},{"name":"소고기","emoji":"🥩","keyword":"소고기 국거리"},{"name":"참기름","emoji":"🫙","keyword":"참기름"},{"name":"국간장","emoji":"🫙","keyword":"국간장"}]', '미역국 밀키트', ARRAY['건강','생일']),
('된장국', ARRAY['아침'], '한식', '[{"name":"된장","emoji":"🫙","keyword":"된장"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"애호박","emoji":"🥬","keyword":"애호박"},{"name":"멸치육수","emoji":"🐟","keyword":"멸치육수"}]', NULL, ARRAY['간단','15분']),
('고구마구이', ARRAY['아침'], '한식', '[{"name":"고구마","emoji":"🍠","keyword":"고구마"}]', NULL, ARRAY['건강','간단','다이어트']),
('감자구이', ARRAY['아침'], '한식', '[{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"버터","emoji":"🧈","keyword":"버터"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', NULL, ARRAY['간단','건강']),
('크로와상', ARRAY['아침'], '양식', '[{"name":"크로와상","emoji":"🥐","keyword":"크로와상"},{"name":"버터","emoji":"🧈","keyword":"버터"},{"name":"잼","emoji":"🍓","keyword":"딸기잼"}]', NULL, ARRAY['간단','5분']),
('베이글', ARRAY['아침'], '양식', '[{"name":"베이글","emoji":"🥯","keyword":"베이글"},{"name":"크림치즈","emoji":"🧀","keyword":"크림치즈"},{"name":"연어","emoji":"🐟","keyword":"훈제연어"}]', NULL, ARRAY['간단','든든']),
('시리얼', ARRAY['아침'], '양식', '[{"name":"시리얼","emoji":"🌾","keyword":"시리얼"},{"name":"우유","emoji":"🥛","keyword":"우유"}]', NULL, ARRAY['간단','5분','혼밥']),
('그릭요거트', ARRAY['아침'], '양식', '[{"name":"그릭요거트","emoji":"🥛","keyword":"그릭요거트"},{"name":"꿀","emoji":"🍯","keyword":"꿀"},{"name":"견과류","emoji":"🥜","keyword":"견과류"}]', NULL, ARRAY['건강','간단','다이어트']),
('주먹밥', ARRAY['아침'], '한식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"참치캔","emoji":"🐟","keyword":"참치캔"},{"name":"김","emoji":"🟫","keyword":"김"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', NULL, ARRAY['간단','도시락']),
('토마토수프', ARRAY['아침'], '양식', '[{"name":"토마토","emoji":"🍅","keyword":"토마토"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"생크림","emoji":"🥛","keyword":"생크림"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', '토마토수프 밀키트', ARRAY['건강','따뜻한']),
('콘수프', ARRAY['아침'], '양식', '[{"name":"옥수수","emoji":"🌽","keyword":"옥수수캔"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', '콘수프 밀키트', ARRAY['간단','따뜻한']),
('닭가슴살샐러드', ARRAY['아침'], '양식', '[{"name":"닭가슴살","emoji":"🍗","keyword":"닭가슴살"},{"name":"양상추","emoji":"🥬","keyword":"양상추"},{"name":"방울토마토","emoji":"🍅","keyword":"방울토마토"},{"name":"드레싱","emoji":"🫙","keyword":"샐러드드레싱"}]', NULL, ARRAY['건강','다이어트']),
('계란죽', ARRAY['아침'], '한식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"참기름","emoji":"🫙","keyword":"참기름"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', NULL, ARRAY['건강','회복식','간단']),
('두유', ARRAY['아침'], '한식', '[{"name":"두유","emoji":"🥛","keyword":"두유"},{"name":"바나나","emoji":"🍌","keyword":"바나나"}]', NULL, ARRAY['건강','간단','5분']),
('머핀', ARRAY['아침'], '양식', '[{"name":"머핀믹스","emoji":"🧁","keyword":"머핀믹스"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', NULL, ARRAY['주말','베이킹']),
('에그머핀', ARRAY['아침'], '양식', '[{"name":"영국식머핀","emoji":"🍞","keyword":"잉글리시머핀"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"햄","emoji":"🥩","keyword":"햄"},{"name":"치즈","emoji":"🧀","keyword":"슬라이스치즈"}]', NULL, ARRAY['든든','15분']),
('김치볶음밥', ARRAY['아침','점심'], '한식', '[{"name":"김치","emoji":"🥬","keyword":"김치"},{"name":"쌀밥","emoji":"🍚","keyword":"쌀"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '김치볶음밥 밀키트', ARRAY['간단','15분','혼밥']),
('누룽지', ARRAY['아침'], '한식', '[{"name":"누룽지","emoji":"🌾","keyword":"누룽지"},{"name":"물","emoji":"💧","keyword":""}]', NULL, ARRAY['간단','건강','어르신']),
('떡국', ARRAY['아침'], '한식', '[{"name":"떡국떡","emoji":"🍚","keyword":"떡국떡"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"국간장","emoji":"🫙","keyword":"국간장"}]', '떡국 밀키트', ARRAY['명절','든든']),
('수란', ARRAY['아침'], '양식', '[{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"식초","emoji":"🫙","keyword":"식초"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', NULL, ARRAY['건강','10분']),
('베이컨에그', ARRAY['아침'], '양식', '[{"name":"베이컨","emoji":"🥓","keyword":"베이컨"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', NULL, ARRAY['든든','10분']),
('참치김밥', ARRAY['아침'], '한식', '[{"name":"참치캔","emoji":"🐟","keyword":"참치캔"},{"name":"김","emoji":"🟫","keyword":"김"},{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"단무지","emoji":"🟡","keyword":"단무지"},{"name":"당근","emoji":"🥕","keyword":"당근"}]', NULL, ARRAY['도시락','든든']),
('고구마라떼', ARRAY['아침'], '한식', '[{"name":"고구마","emoji":"🍠","keyword":"고구마"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"꿀","emoji":"🍯","keyword":"꿀"}]', NULL, ARRAY['간단','달콤']),
('단호박죽', ARRAY['아침'], '한식', '[{"name":"단호박","emoji":"🎃","keyword":"단호박"},{"name":"쌀가루","emoji":"🌾","keyword":"쌀가루"},{"name":"설탕","emoji":"🍬","keyword":"설탕"}]', '단호박죽 밀키트', ARRAY['건강','달콤']),
('두부스크램블', ARRAY['아침'], '양식', '[{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"버터","emoji":"🧈","keyword":"버터"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', NULL, ARRAY['건강','다이어트','10분']),
('요거트파르페', ARRAY['아침'], '양식', '[{"name":"그릭요거트","emoji":"🥛","keyword":"그릭요거트"},{"name":"그래놀라","emoji":"🌾","keyword":"그래놀라"},{"name":"딸기","emoji":"🍓","keyword":"딸기"},{"name":"꿀","emoji":"🍯","keyword":"꿀"}]', NULL, ARRAY['건강','간단','예쁜']),
('치아씨드푸딩', ARRAY['아침'], '양식', '[{"name":"치아씨드","emoji":"🌾","keyword":"치아씨드"},{"name":"우유","emoji":"🥛","keyword":"우유"},{"name":"꿀","emoji":"🍯","keyword":"꿀"},{"name":"바나나","emoji":"🍌","keyword":"바나나"}]', NULL, ARRAY['건강','다이어트','전날준비']),
('소시지볶음', ARRAY['아침'], '한식', '[{"name":"소시지","emoji":"🌭","keyword":"소시지"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"피망","emoji":"🫑","keyword":"피망"},{"name":"케찹","emoji":"🍅","keyword":"케찹"}]', NULL, ARRAY['간단','10분','아이반찬']),
('감자해시브라운', ARRAY['아침'], '양식', '[{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"버터","emoji":"🧈","keyword":"버터"},{"name":"소금","emoji":"🧂","keyword":"소금"},{"name":"후추","emoji":"🧂","keyword":"후추"}]', NULL, ARRAY['10분','든든']),
('쌀국수', ARRAY['아침','점심'], '아시안', '[{"name":"쌀국수면","emoji":"🍜","keyword":"쌀국수"},{"name":"닭육수","emoji":"🍗","keyword":"닭육수"},{"name":"숙주","emoji":"🌿","keyword":"숙주"},{"name":"라임","emoji":"🍋","keyword":"라임"}]', '쌀국수 밀키트', ARRAY['건강','국물']),
('브런치플레이트', ARRAY['아침'], '양식', '[{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"베이컨","emoji":"🥓","keyword":"베이컨"},{"name":"토마토","emoji":"🍅","keyword":"토마토"},{"name":"식빵","emoji":"🍞","keyword":"식빵"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', NULL, ARRAY['주말','든든','특별한날']);

-- 점심 (44)
INSERT INTO public.menu_recipes (name, meal_type, category, ingredients, milkit_keyword, tags) VALUES
('김치찌개', ARRAY['점심','저녁'], '한식', '[{"name":"김치","emoji":"🥬","keyword":"김치"},{"name":"돼지고기","emoji":"🐷","keyword":"돼지고기 앞다리"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"고춧가루","emoji":"🌶️","keyword":"고춧가루"}]', '김치찌개 밀키트', ARRAY['한식','국물','든든']),
('된장찌개', ARRAY['점심','저녁'], '한식', '[{"name":"된장","emoji":"🫙","keyword":"된장"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"애호박","emoji":"🥬","keyword":"애호박"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"멸치육수","emoji":"🐟","keyword":"멸치육수"}]', '된장찌개 밀키트', ARRAY['한식','국물','건강']),
('순두부찌개', ARRAY['점심','저녁'], '한식', '[{"name":"순두부","emoji":"⬜","keyword":"순두부"},{"name":"해물","emoji":"🦐","keyword":"해물모음"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"고춧가루","emoji":"🌶️","keyword":"고춧가루"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', '순두부찌개 밀키트', ARRAY['한식','국물','매운맛']),
('비빔밥', ARRAY['점심'], '한식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"시금치","emoji":"🥬","keyword":"시금치"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '비빔밥 밀키트', ARRAY['건강','한식']),
('라면', ARRAY['점심','야식'], '한식', '[{"name":"라면","emoji":"🍜","keyword":"신라면"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', NULL, ARRAY['간단','5분','혼밥']),
('볶음밥', ARRAY['점심','아침'], '한식', '[{"name":"쌀밥","emoji":"🍚","keyword":"쌀"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"간장","emoji":"🫙","keyword":"간장"}]', '볶음밥 밀키트', ARRAY['간단','15분','혼밥']),
('국밥', ARRAY['점심'], '한식', '[{"name":"돼지뼈","emoji":"🦴","keyword":"돼지뼈"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"깍두기","emoji":"🥬","keyword":"깍두기"},{"name":"새우젓","emoji":"🦐","keyword":"새우젓"}]', '국밥 밀키트', ARRAY['든든','국물','해장']),
('냉면', ARRAY['점심'], '한식', '[{"name":"냉면","emoji":"🍜","keyword":"냉면"},{"name":"오이","emoji":"🥒","keyword":"오이"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"고추냉이","emoji":"🌿","keyword":"고추냉이"}]', '냉면 밀키트', ARRAY['여름','시원한']),
('비빔냉면', ARRAY['점심'], '한식', '[{"name":"냉면","emoji":"🍜","keyword":"냉면"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"오이","emoji":"🥒","keyword":"오이"},{"name":"계란","emoji":"🥚","keyword":"계란"}]', '비빔냉면 밀키트', ARRAY['여름','매운맛']),
('칼국수', ARRAY['점심'], '한식', '[{"name":"칼국수면","emoji":"🍜","keyword":"칼국수면"},{"name":"닭육수","emoji":"🍗","keyword":"닭육수"},{"name":"애호박","emoji":"🥬","keyword":"애호박"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', '칼국수 밀키트', ARRAY['국물','든든']),
('수제비', ARRAY['점심'], '한식', '[{"name":"밀가루","emoji":"🌾","keyword":"밀가루"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"애호박","emoji":"🥬","keyword":"애호박"},{"name":"멸치육수","emoji":"🐟","keyword":"멸치육수"}]', NULL, ARRAY['국물','든든']),
('떡볶이', ARRAY['점심','야식'], '한식', '[{"name":"떡볶이떡","emoji":"🍡","keyword":"떡볶이떡"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"어묵","emoji":"🍢","keyword":"어묵"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"설탕","emoji":"🍬","keyword":"설탕"}]', '떡볶이 밀키트', ARRAY['분식','매운맛','간식']),
('제육볶음', ARRAY['점심','저녁'], '한식', '[{"name":"돼지고기","emoji":"🐷","keyword":"돼지고기 앞다리"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '제육볶음 밀키트', ARRAY['한식','매운맛','든든']),
('돈까스', ARRAY['점심'], '일식', '[{"name":"돼지고기","emoji":"🐷","keyword":"돈까스용 돼지고기"},{"name":"빵가루","emoji":"🌾","keyword":"빵가루"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"돈까스소스","emoji":"🫙","keyword":"돈까스소스"}]', '돈까스 밀키트', ARRAY['일식','든든']),
('김밥', ARRAY['점심','아침'], '한식', '[{"name":"김","emoji":"🟫","keyword":"김"},{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"시금치","emoji":"🥬","keyword":"시금치"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"단무지","emoji":"🟡","keyword":"단무지"},{"name":"계란","emoji":"🥚","keyword":"계란"}]', NULL, ARRAY['도시락','한식']),
('우동', ARRAY['점심'], '일식', '[{"name":"우동면","emoji":"🍜","keyword":"우동면"},{"name":"다시마육수","emoji":"🌿","keyword":"다시마"},{"name":"어묵","emoji":"🍢","keyword":"어묵"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', '우동 밀키트', ARRAY['일식','국물','간단']),
('파스타', ARRAY['점심','저녁','아침'], '양식', '[{"name":"파스타면","emoji":"🍝","keyword":"파스타면"},{"name":"올리브오일","emoji":"🫙","keyword":"올리브오일"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"페페론치노","emoji":"🌶️","keyword":"페페론치노"}]', '파스타 밀키트', ARRAY['양식','간단','혼밥']),
('크림파스타', ARRAY['점심','저녁'], '양식', '[{"name":"파스타면","emoji":"🍝","keyword":"파스타면"},{"name":"생크림","emoji":"🥛","keyword":"생크림"},{"name":"베이컨","emoji":"🥓","keyword":"베이컨"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"마늘","emoji":"🧄","keyword":"마늘"}]', '크림파스타 밀키트', ARRAY['양식','든든']),
('토마토파스타', ARRAY['점심','저녁'], '양식', '[{"name":"파스타면","emoji":"🍝","keyword":"파스타면"},{"name":"토마토소스","emoji":"🍅","keyword":"토마토소스"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"올리브오일","emoji":"🫙","keyword":"올리브오일"}]', '토마토파스타 밀키트', ARRAY['양식','건강']),
('카레라이스', ARRAY['점심','저녁'], '아시안', '[{"name":"카레가루","emoji":"🟡","keyword":"카레가루"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"돼지고기","emoji":"🐷","keyword":"돼지고기"}]', '카레 밀키트', ARRAY['간단','든든','아이반찬']),
('오므라이스', ARRAY['점심'], '양식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"케찹","emoji":"🍅","keyword":"케찹"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', '오므라이스 밀키트', ARRAY['양식','아이반찬']),
('햄버거', ARRAY['점심','야식'], '양식', '[{"name":"햄버거번","emoji":"🍔","keyword":"햄버거번"},{"name":"소고기패티","emoji":"🥩","keyword":"소고기패티"},{"name":"양상추","emoji":"🥬","keyword":"양상추"},{"name":"토마토","emoji":"🍅","keyword":"토마토"},{"name":"치즈","emoji":"🧀","keyword":"슬라이스치즈"}]', NULL, ARRAY['양식','든든']),
('쫄면', ARRAY['점심'], '한식', '[{"name":"쫄면","emoji":"🍜","keyword":"쫄면"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"오이","emoji":"🥒","keyword":"오이"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"계란","emoji":"🥚","keyword":"계란"}]', NULL, ARRAY['분식','매운맛']),
('비빔국수', ARRAY['점심'], '한식', '[{"name":"소면","emoji":"🍜","keyword":"소면"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"오이","emoji":"🥒","keyword":"오이"},{"name":"참기름","emoji":"🫙","keyword":"참기름"},{"name":"깨","emoji":"🌾","keyword":"참깨"}]', NULL, ARRAY['여름','간단','시원한']),
('닭갈비', ARRAY['점심','저녁'], '한식', '[{"name":"닭고기","emoji":"🍗","keyword":"닭갈비용 닭"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"고구마","emoji":"🍠","keyword":"고구마"},{"name":"양배추","emoji":"🥬","keyword":"양배추"},{"name":"떡","emoji":"🍡","keyword":"떡볶이떡"}]', '닭갈비 밀키트', ARRAY['한식','매운맛','든든']),
('샐러드', ARRAY['점심','아침'], '양식', '[{"name":"양상추","emoji":"🥬","keyword":"양상추"},{"name":"방울토마토","emoji":"🍅","keyword":"방울토마토"},{"name":"오이","emoji":"🥒","keyword":"오이"},{"name":"드레싱","emoji":"🫙","keyword":"샐러드드레싱"}]', NULL, ARRAY['건강','다이어트','간단']),
('부대찌개', ARRAY['점심','저녁'], '한식', '[{"name":"햄","emoji":"🥩","keyword":"스팸"},{"name":"소시지","emoji":"🌭","keyword":"소시지"},{"name":"김치","emoji":"🥬","keyword":"김치"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"라면사리","emoji":"🍜","keyword":"사리면"}]', '부대찌개 밀키트', ARRAY['한식','든든','매운맛']),
('소바', ARRAY['점심'], '일식', '[{"name":"소바면","emoji":"🍜","keyword":"소바면"},{"name":"쯔유","emoji":"🫙","keyword":"쯔유"},{"name":"무","emoji":"⬜","keyword":"무"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', NULL, ARRAY['일식','여름','시원한']),
('라볶이', ARRAY['점심','야식'], '한식', '[{"name":"라면","emoji":"🍜","keyword":"라면"},{"name":"떡볶이떡","emoji":"🍡","keyword":"떡볶이떡"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"어묵","emoji":"🍢","keyword":"어묵"}]', NULL, ARRAY['분식','매운맛','혼밥']),
('치킨덮밥', ARRAY['점심'], '한식', '[{"name":"닭가슴살","emoji":"🍗","keyword":"닭가슴살"},{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"양파","emoji":"🧅","keyword":"양파"}]', '치킨덮밥 밀키트', ARRAY['건강','간단']),
('참치마요덮밥', ARRAY['점심'], '한식', '[{"name":"참치캔","emoji":"🐟","keyword":"참치캔"},{"name":"마요네즈","emoji":"🫙","keyword":"마요네즈"},{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"김","emoji":"🟫","keyword":"김"}]', NULL, ARRAY['간단','혼밥','10분']),
('규동', ARRAY['점심'], '일식', '[{"name":"소고기","emoji":"🥩","keyword":"소고기 불고기"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"설탕","emoji":"🍬","keyword":"설탕"},{"name":"쌀","emoji":"🌾","keyword":"쌀"}]', '규동 밀키트', ARRAY['일식','간단']),
('마파두부', ARRAY['점심','저녁'], '중식', '[{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"다진돼지고기","emoji":"🐷","keyword":"다진돼지고기"},{"name":"두반장","emoji":"🌶️","keyword":"두반장"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"마늘","emoji":"🧄","keyword":"마늘"}]', '마파두부 밀키트', ARRAY['중식','매운맛']),
('짜장면', ARRAY['점심'], '중식', '[{"name":"짜장면","emoji":"🍜","keyword":"짜장면"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"돼지고기","emoji":"🐷","keyword":"돼지고기"}]', '짜장 밀키트', ARRAY['중식','간단']),
('짬뽕', ARRAY['점심'], '중식', '[{"name":"짬뽕면","emoji":"🍜","keyword":"짬뽕"},{"name":"해물","emoji":"🦐","keyword":"해물모음"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"고추기름","emoji":"🌶️","keyword":"고추기름"}]', '짬뽕 밀키트', ARRAY['중식','매운맛','국물']),
('탄탄면', ARRAY['점심'], '중식', '[{"name":"라면","emoji":"🍜","keyword":"탄탄면"},{"name":"참깨페이스트","emoji":"🌾","keyword":"참깨페이스트"},{"name":"다진돼지고기","emoji":"🐷","keyword":"다진돼지고기"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', '탄탄면 밀키트', ARRAY['중식','매운맛']),
('클램차우더', ARRAY['점심'], '양식', '[{"name":"조개","emoji":"🐚","keyword":"조개"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"생크림","emoji":"🥛","keyword":"생크림"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', '클램차우더 밀키트', ARRAY['양식','국물','든든']),
('월남쌈', ARRAY['점심'], '아시안', '[{"name":"라이스페이퍼","emoji":"⬜","keyword":"라이스페이퍼"},{"name":"새우","emoji":"🦐","keyword":"새우"},{"name":"당면","emoji":"🍜","keyword":"당면"},{"name":"상추","emoji":"🥬","keyword":"상추"},{"name":"땅콩소스","emoji":"🥜","keyword":"땅콩소스"}]', '월남쌈 밀키트', ARRAY['아시안','건강','파티']),
('팟타이', ARRAY['점심'], '아시안', '[{"name":"쌀국수면","emoji":"🍜","keyword":"쌀국수"},{"name":"새우","emoji":"🦐","keyword":"새우"},{"name":"숙주","emoji":"🌿","keyword":"숙주"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"피시소스","emoji":"🫙","keyword":"피시소스"}]', '팟타이 밀키트', ARRAY['아시안','간단']),
('계란찜', ARRAY['점심'], '한식', '[{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"멸치육수","emoji":"🐟","keyword":"멸치육수"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', NULL, ARRAY['한식','부드러운','아이반찬']),
('갈비탕', ARRAY['점심','저녁'], '한식', '[{"name":"갈비","emoji":"🍖","keyword":"갈비"},{"name":"무","emoji":"⬜","keyword":"무"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"마늘","emoji":"🧄","keyword":"마늘"}]', '갈비탕 밀키트', ARRAY['한식','국물','든든','특별한날']),
('삼계탕', ARRAY['점심','저녁'], '한식', '[{"name":"영계","emoji":"🍗","keyword":"삼계탕용 닭"},{"name":"찹쌀","emoji":"🌾","keyword":"찹쌀"},{"name":"인삼","emoji":"🌿","keyword":"인삼"},{"name":"대추","emoji":"🔴","keyword":"대추"},{"name":"마늘","emoji":"🧄","keyword":"마늘"}]', '삼계탕 밀키트', ARRAY['한식','보양식','여름']),
('설렁탕', ARRAY['점심'], '한식', '[{"name":"사골","emoji":"🦴","keyword":"사골"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"소면","emoji":"🍜","keyword":"소면"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', '설렁탕 밀키트', ARRAY['한식','국물','든든']);

-- 저녁 (31)
INSERT INTO public.menu_recipes (name, meal_type, category, ingredients, milkit_keyword, tags) VALUES
('삼겹살', ARRAY['저녁'], '한식', '[{"name":"삼겹살","emoji":"🥩","keyword":"삼겹살"},{"name":"상추","emoji":"🥬","keyword":"쌈채소"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"쌈장","emoji":"🫙","keyword":"쌈장"},{"name":"김치","emoji":"🥬","keyword":"김치"}]', NULL, ARRAY['한식','파티','주말']),
('불고기', ARRAY['저녁'], '한식', '[{"name":"소고기","emoji":"🥩","keyword":"소고기 불고기"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"설탕","emoji":"🍬","keyword":"설탕"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '불고기 밀키트', ARRAY['한식','특별한날']),
('갈비찜', ARRAY['저녁'], '한식', '[{"name":"갈비","emoji":"🍖","keyword":"갈비"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"설탕","emoji":"🍬","keyword":"설탕"}]', '갈비찜 밀키트', ARRAY['한식','특별한날','명절']),
('닭볶음탕', ARRAY['저녁'], '한식', '[{"name":"닭고기","emoji":"🍗","keyword":"닭볶음탕용 닭"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"간장","emoji":"🫙","keyword":"간장"}]', '닭볶음탕 밀키트', ARRAY['한식','매운맛','든든']),
('찜닭', ARRAY['저녁'], '한식', '[{"name":"닭고기","emoji":"🍗","keyword":"찜닭용 닭"},{"name":"당면","emoji":"🍜","keyword":"당면"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"고추","emoji":"🌶️","keyword":"청양고추"}]', '찜닭 밀키트', ARRAY['한식','든든']),
('스테이크', ARRAY['저녁'], '양식', '[{"name":"소고기","emoji":"🥩","keyword":"스테이크용 소고기"},{"name":"버터","emoji":"🧈","keyword":"버터"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"로즈마리","emoji":"🌿","keyword":"로즈마리"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', NULL, ARRAY['양식','특별한날','주말']),
('함박스테이크', ARRAY['저녁'], '양식', '[{"name":"다진소고기","emoji":"🥩","keyword":"다진소고기"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"빵가루","emoji":"🌾","keyword":"빵가루"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"데미글라스소스","emoji":"🫙","keyword":"데미글라스소스"}]', '함박스테이크 밀키트', ARRAY['양식','든든']),
('치킨', ARRAY['저녁','야식'], '한식', '[{"name":"닭고기","emoji":"🍗","keyword":"닭고기"},{"name":"튀김가루","emoji":"🌾","keyword":"튀김가루"},{"name":"식용유","emoji":"🫙","keyword":"식용유"},{"name":"양념소스","emoji":"🫙","keyword":"치킨양념"}]', NULL, ARRAY['한식','파티','야식']),
('피자', ARRAY['저녁','야식'], '양식', '[{"name":"피자도우","emoji":"🍕","keyword":"피자도우"},{"name":"토마토소스","emoji":"🍅","keyword":"토마토소스"},{"name":"모짜렐라치즈","emoji":"🧀","keyword":"모짜렐라치즈"},{"name":"토핑재료","emoji":"🥩","keyword":"피자토핑"}]', NULL, ARRAY['양식','파티','야식']),
('초밥', ARRAY['저녁'], '일식', '[{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"연어","emoji":"🐟","keyword":"연어"},{"name":"참치","emoji":"🐟","keyword":"참치"},{"name":"새우","emoji":"🦐","keyword":"새우"},{"name":"와사비","emoji":"🌿","keyword":"와사비"}]', '초밥 밀키트', ARRAY['일식','특별한날']),
('회덮밥', ARRAY['저녁'], '한식', '[{"name":"모둠회","emoji":"🐟","keyword":"모둠회"},{"name":"쌀","emoji":"🌾","keyword":"쌀"},{"name":"오이","emoji":"🥒","keyword":"오이"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', NULL, ARRAY['한식','건강','특별한날']),
('낙지볶음', ARRAY['저녁'], '한식', '[{"name":"낙지","emoji":"🐙","keyword":"낙지"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '낙지볶음 밀키트', ARRAY['한식','매운맛','해산물']),
('쭈꾸미볶음', ARRAY['저녁'], '한식', '[{"name":"쭈꾸미","emoji":"🐙","keyword":"쭈꾸미"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"깻잎","emoji":"🌿","keyword":"깻잎"}]', '쭈꾸미볶음 밀키트', ARRAY['한식','매운맛','해산물']),
('두부김치', ARRAY['저녁'], '한식', '[{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"김치","emoji":"🥬","keyword":"김치"},{"name":"돼지고기","emoji":"🐷","keyword":"돼지고기"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', NULL, ARRAY['한식','간단','술안주']),
('보쌈', ARRAY['저녁','야식'], '한식', '[{"name":"돼지고기","emoji":"🐷","keyword":"보쌈용 돼지고기"},{"name":"상추","emoji":"🥬","keyword":"쌈채소"},{"name":"새우젓","emoji":"🦐","keyword":"새우젓"},{"name":"마늘","emoji":"🧄","keyword":"마늘"}]', '보쌈 밀키트', ARRAY['한식','파티','술안주']),
('족발', ARRAY['저녁','야식'], '한식', '[{"name":"족발","emoji":"🐷","keyword":"족발"},{"name":"상추","emoji":"🥬","keyword":"쌈채소"},{"name":"새우젓","emoji":"🦐","keyword":"새우젓"},{"name":"마늘","emoji":"🧄","keyword":"마늘"}]', '족발 밀키트', ARRAY['한식','파티','야식']),
('감자탕', ARRAY['저녁'], '한식', '[{"name":"돼지등뼈","emoji":"🦴","keyword":"돼지등뼈"},{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"들깨가루","emoji":"🌾","keyword":"들깨가루"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', '감자탕 밀키트', ARRAY['한식','국물','든든']),
('곱창전골', ARRAY['저녁'], '한식', '[{"name":"곱창","emoji":"🍖","keyword":"곱창"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"당면","emoji":"🍜","keyword":"당면"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"}]', '곱창전골 밀키트', ARRAY['한식','술안주','특별한날']),
('해물파전', ARRAY['저녁'], '한식', '[{"name":"해물","emoji":"🦐","keyword":"해물모음"},{"name":"파","emoji":"🌿","keyword":"쪽파"},{"name":"밀가루","emoji":"🌾","keyword":"부침가루"},{"name":"계란","emoji":"🥚","keyword":"계란"}]', NULL, ARRAY['한식','술안주','비오는날']),
('잡채', ARRAY['저녁'], '한식', '[{"name":"당면","emoji":"🍜","keyword":"당면"},{"name":"소고기","emoji":"🥩","keyword":"소고기"},{"name":"시금치","emoji":"🥬","keyword":"시금치"},{"name":"당근","emoji":"🥕","keyword":"당근"},{"name":"간장","emoji":"🫙","keyword":"간장"}]', '잡채 밀키트', ARRAY['한식','명절','파티']),
('샤브샤브', ARRAY['저녁'], '일식', '[{"name":"소고기","emoji":"🥩","keyword":"샤브샤브용 소고기"},{"name":"배추","emoji":"🥬","keyword":"배추"},{"name":"팽이버섯","emoji":"🍄","keyword":"팽이버섯"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"폰즈소스","emoji":"🫙","keyword":"폰즈소스"}]', '샤브샤브 밀키트', ARRAY['일식','파티','건강']),
('오삼불고기', ARRAY['저녁'], '한식', '[{"name":"오징어","emoji":"🦑","keyword":"오징어"},{"name":"삼겹살","emoji":"🥩","keyword":"삼겹살"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"양파","emoji":"🧅","keyword":"양파"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', '오삼불고기 밀키트', ARRAY['한식','매운맛','든든']),
('마라탕', ARRAY['저녁','야식'], '중식', '[{"name":"마라소스","emoji":"🌶️","keyword":"마라소스"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"당면","emoji":"🍜","keyword":"당면"},{"name":"어묵","emoji":"🍢","keyword":"어묵"},{"name":"숙주","emoji":"🌿","keyword":"숙주"}]', '마라탕 밀키트', ARRAY['중식','매운맛','유행']),
('탕수육', ARRAY['저녁'], '중식', '[{"name":"돼지고기","emoji":"🐷","keyword":"돼지고기"},{"name":"전분","emoji":"🌾","keyword":"전분"},{"name":"식초","emoji":"🫙","keyword":"식초"},{"name":"케찹","emoji":"🍅","keyword":"케찹"},{"name":"파인애플","emoji":"🍍","keyword":"파인애플통조림"}]', '탕수육 밀키트', ARRAY['중식','파티','아이반찬']),
('깐풍기', ARRAY['저녁'], '중식', '[{"name":"닭고기","emoji":"🍗","keyword":"닭고기"},{"name":"고추","emoji":"🌶️","keyword":"청양고추"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"식초","emoji":"🫙","keyword":"식초"}]', '깐풍기 밀키트', ARRAY['중식','매운맛']),
('연어스테이크', ARRAY['저녁'], '양식', '[{"name":"연어","emoji":"🐟","keyword":"연어"},{"name":"버터","emoji":"🧈","keyword":"버터"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"레몬","emoji":"🍋","keyword":"레몬"},{"name":"아스파라거스","emoji":"🌿","keyword":"아스파라거스"}]', NULL, ARRAY['양식','건강','특별한날']),
('치즈닭갈비', ARRAY['저녁'], '한식', '[{"name":"닭고기","emoji":"🍗","keyword":"닭갈비용 닭"},{"name":"모짜렐라치즈","emoji":"🧀","keyword":"모짜렐라치즈"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"양배추","emoji":"🥬","keyword":"양배추"},{"name":"고구마","emoji":"🍠","keyword":"고구마"}]', '치즈닭갈비 밀키트', ARRAY['한식','매운맛','치즈']),
('등갈비구이', ARRAY['저녁'], '한식', '[{"name":"등갈비","emoji":"🍖","keyword":"등갈비"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"생강","emoji":"🫚","keyword":"생강"},{"name":"설탕","emoji":"🍬","keyword":"설탕"}]', '등갈비 밀키트', ARRAY['한식','주말','특별한날']),
('해물찜', ARRAY['저녁'], '한식', '[{"name":"꽃게","emoji":"🦀","keyword":"꽃게"},{"name":"새우","emoji":"🦐","keyword":"새우"},{"name":"조개","emoji":"🐚","keyword":"조개"},{"name":"콩나물","emoji":"🌿","keyword":"콩나물"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"}]', '해물찜 밀키트', ARRAY['한식','해산물','특별한날']),
('순대국밥', ARRAY['저녁'], '한식', '[{"name":"순대","emoji":"🌭","keyword":"순대"},{"name":"돼지뼈","emoji":"🦴","keyword":"돼지뼈"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"새우젓","emoji":"🦐","keyword":"새우젓"}]', NULL, ARRAY['한식','국물','해장']),
('육개장', ARRAY['저녁'], '한식', '[{"name":"소고기","emoji":"🥩","keyword":"소고기 국거리"},{"name":"고사리","emoji":"🌿","keyword":"고사리"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"고춧가루","emoji":"🌶️","keyword":"고춧가루"},{"name":"참기름","emoji":"🫙","keyword":"참기름"}]', '육개장 밀키트', ARRAY['한식','국물','매운맛']);

-- 야식 (40)
INSERT INTO public.menu_recipes (name, meal_type, category, ingredients, milkit_keyword, tags) VALUES
('불닭볶음면', ARRAY['야식'], '한식', '[{"name":"불닭볶음면","emoji":"🍜","keyword":"불닭볶음면"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"치즈","emoji":"🧀","keyword":"슬라이스치즈"}]', NULL, ARRAY['매운맛','간단','혼밥']),
('컵라면', ARRAY['야식'], '한식', '[{"name":"컵라면","emoji":"🍜","keyword":"컵라면"},{"name":"물","emoji":"💧","keyword":""}]', NULL, ARRAY['간단','혼밥','3분']),
('순대', ARRAY['야식'], '한식', '[{"name":"순대","emoji":"🌭","keyword":"순대"},{"name":"어묵","emoji":"🍢","keyword":"어묵"},{"name":"소금","emoji":"🧂","keyword":"소금"},{"name":"깻잎","emoji":"🌿","keyword":"깻잎"}]', NULL, ARRAY['분식','술안주']),
('어묵탕', ARRAY['야식'], '한식', '[{"name":"어묵","emoji":"🍢","keyword":"어묵"},{"name":"무","emoji":"⬜","keyword":"무"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"간장","emoji":"🫙","keyword":"간장"}]', NULL, ARRAY['분식','국물','겨울']),
('핫도그', ARRAY['야식'], '한식', '[{"name":"핫도그","emoji":"🌭","keyword":"핫도그"},{"name":"케찹","emoji":"🍅","keyword":"케찹"},{"name":"머스타드","emoji":"🫙","keyword":"머스타드"}]', NULL, ARRAY['간단','간식']),
('나초', ARRAY['야식'], '양식', '[{"name":"나초","emoji":"🌽","keyword":"나초"},{"name":"살사소스","emoji":"🍅","keyword":"살사소스"},{"name":"치즈소스","emoji":"🧀","keyword":"치즈소스"}]', NULL, ARRAY['양식','파티','술안주']),
('팝콘', ARRAY['야식'], '양식', '[{"name":"팝콘","emoji":"🍿","keyword":"팝콘"},{"name":"버터","emoji":"🧈","keyword":"버터"}]', NULL, ARRAY['간단','영화','간식']),
('감자튀김', ARRAY['야식'], '양식', '[{"name":"감자","emoji":"🥔","keyword":"감자"},{"name":"식용유","emoji":"🫙","keyword":"식용유"},{"name":"소금","emoji":"🧂","keyword":"소금"},{"name":"케찹","emoji":"🍅","keyword":"케찹"}]', NULL, ARRAY['간단','술안주']),
('닭발', ARRAY['야식'], '한식', '[{"name":"닭발","emoji":"🍗","keyword":"닭발"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"마늘","emoji":"🧄","keyword":"마늘"},{"name":"간장","emoji":"🫙","keyword":"간장"}]', '닭발 밀키트', ARRAY['한식','매운맛','술안주']),
('막창', ARRAY['야식'], '한식', '[{"name":"막창","emoji":"🍖","keyword":"막창"},{"name":"된장","emoji":"🫙","keyword":"된장"},{"name":"쌈장","emoji":"🫙","keyword":"쌈장"},{"name":"상추","emoji":"🥬","keyword":"상추"}]', NULL, ARRAY['한식','술안주','특별한날']),
('곱창', ARRAY['야식'], '한식', '[{"name":"곱창","emoji":"🍖","keyword":"곱창"},{"name":"파","emoji":"🌿","keyword":"쪽파"},{"name":"참기름","emoji":"🫙","keyword":"참기름"},{"name":"소금","emoji":"🧂","keyword":"소금"}]', '곱창 밀키트', ARRAY['한식','술안주']),
('소떡소떡', ARRAY['야식'], '한식', '[{"name":"소시지","emoji":"🌭","keyword":"소시지"},{"name":"떡볶이떡","emoji":"🍡","keyword":"떡볶이떡"},{"name":"케찹","emoji":"🍅","keyword":"케찹"},{"name":"머스타드","emoji":"🫙","keyword":"머스타드"}]', NULL, ARRAY['간단','간식','아이반찬']),
('계란빵', ARRAY['야식'], '한식', '[{"name":"계란빵믹스","emoji":"🍞","keyword":"계란빵믹스"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"우유","emoji":"🥛","keyword":"우유"}]', NULL, ARRAY['간단','달콤','겨울']),
('붕어빵', ARRAY['야식'], '한식', '[{"name":"붕어빵믹스","emoji":"🐟","keyword":"붕어빵믹스"},{"name":"팥앙금","emoji":"🔴","keyword":"팥앙금"},{"name":"계란","emoji":"🥚","keyword":"계란"}]', NULL, ARRAY['간단','달콤','겨울']),
('타코야키', ARRAY['야식'], '일식', '[{"name":"타코야키믹스","emoji":"🟤","keyword":"타코야키믹스"},{"name":"문어","emoji":"🐙","keyword":"문어"},{"name":"가다랑어포","emoji":"🐟","keyword":"가다랑어포"},{"name":"마요네즈","emoji":"🫙","keyword":"마요네즈"}]', '타코야키 밀키트', ARRAY['일식','간식','파티']),
('만두', ARRAY['야식','점심'], '한식', '[{"name":"만두","emoji":"🥟","keyword":"만두"},{"name":"간장","emoji":"🫙","keyword":"간장"},{"name":"식초","emoji":"🫙","keyword":"식초"}]', NULL, ARRAY['간단','간식','아이반찬']),
('군만두', ARRAY['야식'], '한식', '[{"name":"만두","emoji":"🥟","keyword":"만두"},{"name":"식용유","emoji":"🫙","keyword":"식용유"},{"name":"간장","emoji":"🫙","keyword":"간장"}]', NULL, ARRAY['간단','술안주','간식']),
('피맥', ARRAY['야식'], '양식', '[{"name":"피자","emoji":"🍕","keyword":"피자"},{"name":"맥주","emoji":"🍺","keyword":"맥주"}]', NULL, ARRAY['파티','주말','술안주']),
('치맥', ARRAY['야식'], '한식', '[{"name":"치킨","emoji":"🍗","keyword":"치킨"},{"name":"맥주","emoji":"🍺","keyword":"맥주"},{"name":"치킨무","emoji":"🟡","keyword":"치킨무"}]', NULL, ARRAY['파티','주말','술안주']),
('떡꼬치', ARRAY['야식'], '한식', '[{"name":"떡볶이떡","emoji":"🍡","keyword":"떡볶이떡"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"설탕","emoji":"🍬","keyword":"설탕"}]', NULL, ARRAY['간단','간식','분식']),
('오뎅탕', ARRAY['야식'], '한식', '[{"name":"어묵","emoji":"🍢","keyword":"어묵"},{"name":"무","emoji":"⬜","keyword":"무"},{"name":"대파","emoji":"🌿","keyword":"대파"},{"name":"다시마","emoji":"🌿","keyword":"다시마"}]', NULL, ARRAY['국물','겨울','간단']),
('즉석떡볶이', ARRAY['야식','점심'], '한식', '[{"name":"즉석떡볶이","emoji":"🍡","keyword":"즉석떡볶이"},{"name":"어묵","emoji":"🍢","keyword":"어묵"},{"name":"계란","emoji":"🥚","keyword":"계란"}]', NULL, ARRAY['간단','매운맛','혼밥']),
('컵밥', ARRAY['야식'], '한식', '[{"name":"컵밥","emoji":"🍚","keyword":"컵밥"},{"name":"물","emoji":"💧","keyword":""}]', NULL, ARRAY['간단','3분','혼밥']),
('냉동피자', ARRAY['야식'], '양식', '[{"name":"냉동피자","emoji":"🍕","keyword":"냉동피자"}]', NULL, ARRAY['간단','5분','혼밥']),
('치즈볼', ARRAY['야식'], '양식', '[{"name":"치즈볼","emoji":"🧀","keyword":"치즈볼"},{"name":"식용유","emoji":"🫙","keyword":"식용유"}]', NULL, ARRAY['간단','간식','파티']),
('감자칩', ARRAY['야식'], '양식', '[{"name":"감자칩","emoji":"🥔","keyword":"감자칩"}]', NULL, ARRAY['간단','간식']),
('새우깡', ARRAY['야식'], '한식', '[{"name":"새우깡","emoji":"🦐","keyword":"새우깡"}]', NULL, ARRAY['간단','간식']),
('라면땅', ARRAY['야식'], '한식', '[{"name":"라면땅","emoji":"🍜","keyword":"라면땅"}]', NULL, ARRAY['간단','간식']),
('오징어게임', ARRAY['야식'], '한식', '[{"name":"오징어","emoji":"🦑","keyword":"오징어"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"마요네즈","emoji":"🫙","keyword":"마요네즈"}]', NULL, ARRAY['술안주','매운맛']),
('골뱅이무침', ARRAY['야식'], '한식', '[{"name":"골뱅이","emoji":"🐚","keyword":"골뱅이통조림"},{"name":"소면","emoji":"🍜","keyword":"소면"},{"name":"오이","emoji":"🥒","keyword":"오이"},{"name":"고추장","emoji":"🌶️","keyword":"고추장"},{"name":"식초","emoji":"🫙","keyword":"식초"}]', NULL, ARRAY['한식','술안주','매운맛']),
('계란찜야식', ARRAY['야식'], '한식', '[{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"멸치육수","emoji":"🐟","keyword":"멸치육수"},{"name":"새우젓","emoji":"🦐","keyword":"새우젓"}]', NULL, ARRAY['간단','부드러운','혼밥']),
('냉동만두전골', ARRAY['야식'], '한식', '[{"name":"냉동만두","emoji":"🥟","keyword":"냉동만두"},{"name":"김치","emoji":"🥬","keyword":"김치"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', NULL, ARRAY['간단','국물','혼밥']),
('짜파게티', ARRAY['야식','점심'], '한식', '[{"name":"짜파게티","emoji":"🍜","keyword":"짜파게티"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"올리브오일","emoji":"🫙","keyword":"올리브오일"}]', NULL, ARRAY['간단','혼밥','5분']),
('너구리라면', ARRAY['야식'], '한식', '[{"name":"너구리","emoji":"🍜","keyword":"너구리"},{"name":"계란","emoji":"🥚","keyword":"계란"},{"name":"대파","emoji":"🌿","keyword":"대파"}]', NULL, ARRAY['간단','국물','혼밥']),
('육포', ARRAY['야식'], '한식', '[{"name":"육포","emoji":"🥩","keyword":"육포"}]', NULL, ARRAY['간단','술안주','단백질']),
('치즈스틱', ARRAY['야식'], '양식', '[{"name":"치즈스틱","emoji":"🧀","keyword":"치즈스틱"},{"name":"식용유","emoji":"🫙","keyword":"식용유"}]', NULL, ARRAY['간단','간식','아이반찬']),
('모듬전', ARRAY['야식'], '한식', '[{"name":"부침가루","emoji":"🌾","keyword":"부침가루"},{"name":"김치","emoji":"🥬","keyword":"김치"},{"name":"해물","emoji":"🦐","keyword":"해물모음"},{"name":"계란","emoji":"🥚","keyword":"계란"}]', NULL, ARRAY['한식','술안주','비오는날']),
('마라샹궈', ARRAY['야식'], '중식', '[{"name":"마라소스","emoji":"🌶️","keyword":"마라소스"},{"name":"새우","emoji":"🦐","keyword":"새우"},{"name":"소고기","emoji":"🥩","keyword":"소고기"},{"name":"두부","emoji":"⬜","keyword":"두부"},{"name":"버섯","emoji":"🍄","keyword":"버섯"}]', '마라샹궈 밀키트', ARRAY['중식','매운맛','유행']),
('냉동삼겹살', ARRAY['야식'], '한식', '[{"name":"냉동삼겹살","emoji":"🥩","keyword":"냉동삼겹살"},{"name":"상추","emoji":"🥬","keyword":"쌈채소"},{"name":"쌈장","emoji":"🫙","keyword":"쌈장"}]', NULL, ARRAY['간단','술안주']),
('참치캔안주', ARRAY['야식'], '한식', '[{"name":"참치캔","emoji":"🐟","keyword":"참치캔"},{"name":"마요네즈","emoji":"🫙","keyword":"마요네즈"},{"name":"김","emoji":"🟫","keyword":"김"}]', NULL, ARRAY['간단','술안주','혼밥']);
